### ISSUE TITLE
Battle screen is all grey

### ISSUE THREAD

**Issue by upbeatDiamond** [Pocket-Godot/Pokemon-Battle#3]
![image](https://user-images.githubusercontent.com/112040252/205467333-9b7314f6-d8c4-4f7e-a69f-3bdef9ec7e2f.png)
![image](https://user-images.githubusercontent.com/112040252/205467364-b401e6fa-9771-4e4d-bda9-3394f7062dbc.png)

I downloaded, unzipped, and pressed 'play', and I got what's on the attached screenshots.

**Comment by upbeatDiamond** [comment]
Error log:

![image](https://user-images.githubusercontent.com/112040252/205467696-4f04478b-0148-4e6e-a347-f40b50df0585.png)

**Comment by mechPenSketch** [comment]
I didn't encounter this problem while play-testing, so I'm not sure how far I can go help you.

The first screenshot shows that it cannot load `res://dialogic/custom-events/battle_anim/EventBlock.tscn`. See whether the file is in the project. Though why would this file had to be called during playtesting when it's meant for editor?

When was the last time you've downloaded the zip? It's possible that you've downloaded at an unfortunate timing while I was working on custom dialog events (though given I've seen the `data` folder in the project, that would be anachronic). Could you download the latest zip and test again.

**Comment by upbeatDiamond** [comment]
Downloading it again, extracting the files again into the same folder, overwriting old files, I'm getting different but very similar errors.

The .../Events/Parts/... path doesn't exist on my zip.

**Comment by upbeatDiamond** [comment]
Inserting files from the latest Dialogic for Godot 3.x commit, I got the game to start.

**Comment by mechPenSketch** [comment]
By "start", do you mean you are able to playtest with no issues?

**Comment by upbeatDiamond** [comment]
I got the sprites to display, and the health bar to drain when selecting any move, when inserting files from the newest Dialogic for Godot 3.5 repo.

**Comment by mechPenSketch** [comment]
In that case, I can safely conclude that your issue is solved.
