### ISSUE TITLE
Version error on install.

### ISSUE THREAD

**Issue by ogrotten** [Pocket-Godot/Pokemon-Battle#7]
In godot 3.5.3, importing gives this error dialog

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/78d2d646-4dcf-4c4f-93f5-5d01e8893701)

Please advise?

**Comment by ogrotten** [comment]
I downloaded 3.2 stable (thank the gods that godot is so self contained) and received this error dialog

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/8c9ad453-659b-4c5c-81c0-1acebdcf81cc)

After trying to open it anyway, I received this in the console

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/4d6b5fdf-758e-434c-b3cf-62c2657d3362)

I opened the `project.godot` file and manually changed the line to read

    config_version=4

Went back to 3.5.3 and the project loaded but with these error dialogs

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/f6a92be3-ec1d-4778-848e-b9f464fcf964)

Running it failed, with this in the debugger

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/1ca3c52b-6cd1-4866-aa2a-398329035fec)

Upon returning to 3.2, the project loads but gives this error dialog

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/2cc62b45-8dc5-47ea-b60a-a5ebfb16046d)

it also spammed the console with this: https://gist.github.com/ogrotten/5ff890f04e8b0b072337cf5d91da7aa9

Alright . . . 

* Deleted the project
* re-cloned this repo
* changed to `config_version = 4`
* opened godot 3.2

Before loading the project, received this in the console:
![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/bcadfa9b-0612-4414-bee7-3ecf2049aad8)

This is the project loader 

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/47561340-008b-439a-baef-0784003c86ad)

Loaded it anyway and received this again:

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/d90c30c0-ee4b-408e-84ce-67952ff4c02f)

Click OK
The screen flashed like it tried to load it, but it went back to the project loader. I had received this in the console.

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/4fefba92-7b2c-4f86-8336-465ad4111f09)

**Comment by ogrotten** [comment]
I tried to be thorough in the troubleshooting and detailing the process. Hope it helps.

**Comment by mechPenSketch** [comment]
Sorry, but since I've brought my project forward to 4.0, it wouldn't be compatible with Godot 3.2. However, you can go download a past release here, which should compatible with Godot 3.2: https://github.com/Pocket-Godot/Pokemon-Battle/releases

Alternatively, you could try to get commit `a3cc8359fc8c95d526c55cafc56f23a9f333a681`, which is before I updated my project to Godot 4.0.

**Comment by ogrotten** [comment]
Ok. Then you should change the readme. That's why I tried it to begin with. 

![image](https://github.com/Pocket-Godot/Pokemon-Battle/assets/8119012/86f66d84-e0c4-456f-bb8c-3a030bdf28a0)
